apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: api-initial
  namespace: vod-backend
  labels:
    app.kubernetes.io/instance: api
    app.kubernetes.io/name: api
    operator.tekton.dev/operand-name: openshift-pipelines-addons
    pipeline.openshift.io/strategy: docker
    pipeline.openshift.io/type: openshift
    tekton.dev/pipeline: api
spec:
  pipelineRef:
    name: api
  params:
  - name: APP_NAME
    value: api
  - name: GIT_REPO
    value: https://github.com/nutanixdev/modern-app-demo.git
  - name: GIT_REVISION
    value: ''
  - name: IMAGE_NAME
    value: image-registry.openshift-image-registry.svc:5000/vod-backend/api
  - name: PATH_CONTEXT
    value: src/api
  resources: []
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        labels:
          tekton.dev/pipeline: api
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  status: