apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: input-validate
  namespace: vod-backend
  labels:
    app: input-validate
    app.kubernetes.io/instance: input-validate
    app.kubernetes.io/component: input-validate
    app.kubernetes.io/name: input-validate
    app.kubernetes.io/part-of: ingest-app
  annotations:
    app.openshift.io/vcs-uri: https://github.com/nutanixdev/modern-app-demo.git
    app.openshift.io/vcs-ref: ''
