apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: encode-nfs
  namespace: vod-backend
spec:
  storageClassName: nutanix-files
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
