apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: mongoprocess-encode
  namespace: vod-backend
  labels:
    eventing.knative.dev/broker: default
spec:
  broker: default
  filter:
    attributes:
      type: com.nutanix.gts.mongoprocess
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: encode
      namespace: vod-backend
