apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: mongoingest-profiler
  namespace: vod-backend
  labels:
    eventing.knative.dev/broker: default
spec:
  broker: default
  filter:
    attributes:
      type: com.nutanix.gts.mongoingest
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: profiler
      namespace: vod-backend
