apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: mongopublish
  namespace: vod-backend
  labels:
    app: mongopublish
    app.kubernetes.io/instance: mongopublish
    app.kubernetes.io/component: mongopublish
    app.kubernetes.io/name: mongopublish
    app.kubernetes.io/part-of: ingest-app
  annotations:
    app.openshift.io/vcs-uri: https://github.com/nutanixdev/modern-app-demo.git
    app.openshift.io/vcs-ref: ''
