apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: output-validate-mongopublish
  namespace: vod-backend
  labels:
    eventing.knative.dev/broker: default
spec:
  broker: default
  filter:
    attributes:
      type: com.nutanix.gts.output-validate
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: mongopublish
      namespace: vod-backend
