apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: frontend-initial
  namespace: vod-frontend
  labels:
    app.kubernetes.io/instance: frontend
    app.kubernetes.io/name: frontend
    operator.tekton.dev/operand-name: openshift-pipelines-addons
    pipeline.openshift.io/strategy: docker
    pipeline.openshift.io/type: openshift
    tekton.dev/pipeline: frontend
spec:
  pipelineRef:
    name: frontend
  params:
  - name: APP_NAME
    value: frontend
  - name: GIT_REPO
    value: https://github.com/nutanixdev/modern-app-demo.git
  - name: GIT_REVISION
    value: ''
  - name: IMAGE_NAME
    value: image-registry.openshift-image-registry.svc:5000/vod-frontend/frontend
  - name: PATH_CONTEXT
    value: src/frontend
  resources: []
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        labels:
          tekton.dev/pipeline: frontend
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  status: