kind: Pipeline
apiVersion: tekton.dev/v1beta1
metadata:
  name: frontend
  namespace: vod-frontend
  labels:
    operator.tekton.dev/operand-name: openshift-pipelines-addons
    pipeline.openshift.io/strategy: docker
    pipeline.openshift.io/type: openshift
    app.kubernetes.io/instance: frontend
    app.kubernetes.io/name: frontend
spec:
  params:
  - name: APP_NAME
    type: string
    default: frontend
  - name: GIT_REPO
    type: string
    default: https://github.com/nutanixdev/modern-app-demo.git
  - name: GIT_REVISION
    type: string
    default: ''
  - name: IMAGE_NAME
    type: string
    default: image-registry.openshift-image-registry.svc:5000/vod-frontend/frontend
  - default: src/frontend
    name: PATH_CONTEXT
    type: string
  tasks:
  - name: fetch-repository
    params:
    - name: url
      value: "$(params.GIT_REPO)"
    - name: revision
      value: "$(params.GIT_REVISION)"
    - name: subdirectory
      value: ''
    - name: deleteExisting
      value: 'true'
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: workspace
  - name: build
    params:
    - name: IMAGE
      value: "$(params.IMAGE_NAME)"
    - name: TLSVERIFY
      value: 'false'
    - name: CONTEXT
      value: "$(params.PATH_CONTEXT)"
    runAfter:
    - fetch-repository
    taskRef:
      kind: ClusterTask
      name: buildah
    workspaces:
    - name: source
      workspace: workspace
  - name: deploy
    params:
    - name: SCRIPT
      value: oc rollout status dc/$(params.APP_NAME)
    runAfter:
    - build
    taskRef:
      kind: ClusterTask
      name: openshift-client
  workspaces:
  - name: workspace